datacamp/design-system

packages/docs/catalog-doc-site/catalog/pages/componentLibrary/button.js, packages/docs/storybook/stories/button.stories.js, packages/react-components/button/src/ButtonGroup/index.tsx, packages/react-components/button/src/CompactButtonGroup/index.tsx, packages/react-components/button/src/SocialMediaButtons/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/SocialMediaButtons/index.spec.tsx, packages/react-components/button/src/SocialMediaButtons/index.tsx, packages/react-components/button/src/index.spec.ts, packages/react-components/button/src/index.ts
=> WF-404 Social media buttons

packages/docs/catalog-doc-site/catalog/pages/index.js
=> WF-465 update brand guidelines pdf

packages/react-components/button/src/Button/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/Button/spinnerStyle.ts
switches from nth-child to nth-of-type to avoid SSR issues
=> WF-476 stop using nth-child selector in loading buttons

packages/react-components/modals/src/Panel/PanelStyles.ts, packages/react-components/modals/src/Panel/__snapshots__/index.spec.tsx.snap
This is a similar fix to #1260, but for panels.
=> fix: add modal positioner fix to panel

.circleci/config.yml, ecs.json, packages/docs/storybook/ecs.backstage.json
Updated following CircleCI orbs:
- datacamp/ecr@1
- datacamp/deploy@2
=> fix: disable documentation deployment

.circleci/config.yml
=> Config staging deployment

.circleci/config.yml, ci/.npmrc, packages/docs/next-doc-site/next.config.js, packages/docs/next-doc-site/package.json
Configured **documentation website** to work on new Cloudlflare CDN.
=> [WF-455] Cloudflare deployment configuration

packages/react-components/button/src/Button/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/UserAccountMenu/__snapshots__/index.spec.tsx.snap, packages/react-components/card/src/__snapshots__/index.spec.tsx.snap, packages/react-components/card/src/index.spec.tsx, packages/react-components/card/src/index.tsx, packages/react-components/modals/src/AlertDialog/__snapshots__/index.spec.tsx.snap, packages/react-components/modals/src/Dialog/__snapshots__/index.spec.tsx.snap, packages/react-components/modals/src/Panel/__snapshots__/index.spec.tsx.snap, packages/react-components/tooltip/src/__snapshots__/index.spec.tsx.snap
Fixed janky animation when hovering over Card with elevation drop shadow.
=> [FIX] Adjust elevation map to remove janky animation

packages/react-components/button/src/Button/index.tsx, packages/react-components/card/src/index.spec.tsx, packages/react-components/card/src/index.tsx
Improvements:
* updated Button's typing of onClick handler to accept event
* pass new onClick prop to Card component
=> Button and Card extra props

packages/docs/next-doc-site/components/code-preview-button.tsx, packages/docs/next-doc-site/components/colors-grid.tsx, packages/docs/next-doc-site/components/constants.ts, packages/docs/next-doc-site/components/download-button.tsx, packages/docs/next-doc-site/components/example.tsx, packages/docs/next-doc-site/components/logo-preview.tsx, packages/docs/next-doc-site/components/navigation-category.tsx, packages/docs/next-doc-site/components/navigation-link.tsx, packages/docs/next-doc-site/components/playground.tsx, packages/docs/next-doc-site/components/sidebar.tsx, packages/docs/next-doc-site/components/table.tsx, packages/docs/next-doc-site/examples/button/social-media.tsx, packages/docs/next-doc-site/package.json, yarn.lock
- Increased spacings between some sections (requested by designers)
- Updated focus style of action elements to be more in line with regular Waffles (using _:focus-visible_, which is not yet supported by Safari, should be fine for docs site for now)
- Added hover style to sidebar navigation items
- Unpinned dependencies
Desktop:
=> [WF-495] Focus styles and spacings

packages/react-components/icons/standardIcons/flashcard.svg
Added **FlashcardIcon** to the collection:
=> Flashcard icon

.circleci/config.yml
Test the new cache-control policies for assets.
=> New cache-control policies on staging

packages/react-components/button/src/index.ts, packages/react-components/form-elements/src/index.tsx, packages/react-components/icons/gulpfile.js, packages/react-components/modals/src/index.tsx, packages/react-components/toast/src/index.tsx
=> Trigger re-release

packages/docs/catalog-doc-site/catalog/pages/content/course-naming-guidelines.md, packages/docs/catalog-doc-site/catalog/pages/content/grammar.md, packages/docs/next-doc-site/pages/content/course-naming.mdx, packages/docs/next-doc-site/pages/content/terminology.mdx
=> [WF-521] Capitalize Plotly in beta docs

packages/docs/catalog-doc-site/catalog/pages/content/course-naming-guidelines.md, packages/docs/catalog-doc-site/catalog/pages/content/grammar.md, packages/docs/next-doc-site/pages/content/course-naming.mdx, packages/docs/next-doc-site/pages/content/terminology.mdx
=> [WF-521] Capitalized Plotly

packages/other/tokens/buildNewTokens.js, packages/react-components/button/src/index.ts, packages/react-components/card/src/index.tsx, packages/react-components/form-elements/src/index.tsx, packages/react-components/icons/gulpfile.js, packages/react-components/loaders/src/index.ts, packages/react-components/markdown/src/index.ts, packages/react-components/modals/src/index.tsx, packages/react-components/text/src/index.ts, packages/react-components/toast/src/index.tsx, packages/react-components/tooltip/src/index.tsx
Republish latest beta packages to NPM. Most likely due to some network error they got there in a broken state.
- ~[ ] Meets acceptance criteria~
- ~[ ] Approved by Designer, Engineer, & PO~
=> [FIX] Broken npm package

packages/stylesheets/flash-banner/lib/_flash-banner.scss
Updated **flash card link color** Sass mixin, so the color better blends with a background.
- ~[ ] Unit tests written & pass CI~
- ~[ ] Tested on [supported browsers](https://support.datacamp.com/hc/en-us/articles/360001541574-Minimum-System-Requirements)~
=> Flash Card link color

packages/react-components/modals/src/BaseDialog/index.tsx, packages/react-components/modals/src/Dialog/__snapshots__/index.spec.tsx.snap, packages/react-components/modals/src/Dialog/index.spec.tsx, packages/react-components/modals/src/Dialog/index.tsx
Allow to pass custom class name to modal's portal via `portalClassName` prop.
=> Modal portalClassName

.circleci/config.yml, README.md, packages/docs/next-doc-site/components/constants.ts, packages/docs/next-doc-site/components/deprecation-banner.tsx, packages/docs/next-doc-site/components/page-header.tsx, packages/docs/next-doc-site/components/page-layout.tsx, packages/docs/next-doc-site/components/sidebar.tsx
Add deprecation warning to Readme and Documentation site (stays always on top):
=> Deprecation warning

.circleci/config.yml, README.md, packages/docs/next-doc-site/components/constants.ts, packages/docs/next-doc-site/components/deprecation-banner.tsx, packages/docs/next-doc-site/components/page-header.tsx, packages/docs/next-doc-site/components/page-layout.tsx, packages/docs/next-doc-site/components/sidebar.tsx
Add deprecation warning to readme and docs website:
=> Deprecation warning (beta)

.circleci/config.yml, package.json, yarn.lock
- Resolve `chokidar` as higher version so  `fsevents`subdependency is `< 1.2.11`
=> [WF-963] - Solve `fsevents` security vunerability
