packages/react-components/icons/package.json
BREAKING CHANGE: this is only a breaking change when using react-native and can be ignored on web. Otherwise react-native-svg is now a peer dependency rather than a direct dependency and will need to be installed to use the mobile icons.
=> WF-471 fix: remove peer dependency warning for react-native

packages/react-components/button/package.json
We are actually still compatible, so to avoid making a breaking change I have just widened the range
=> WF-470 fix: expand range of icons peer dependency to include latest versions

packages/react-components/resizable-elements/src/ResizableElements.tsx, packages/react-components/resizable-elements/src/__snapshots__/ResizableElements.spec.tsx.snap
Might break something, but it's needed by LX, they're the only ones using it atm, so should be fine.
=> fix: remove overflow hidden from resizable elements

packages/other/utils/package.json, packages/other/utils/src/childrenOfType.ts, packages/other/utils/src/index.spec.ts, packages/other/utils/src/index.ts, packages/react-components/button/src/Button/index.tsx, packages/react-components/button/src/ButtonGroup/index.tsx, packages/react-components/button/src/CompactButtonGroup/index.tsx, packages/react-components/form-elements/src/CheckboxList/index.tsx, packages/react-components/form-elements/src/RadioList/index.tsx, packages/react-components/form-elements/src/Select/index.tsx, packages/react-components/modals/src/shared/Footer.tsx, packages/react-components/text/src/components/Emphasis.tsx, packages/react-components/text/src/components/Heading.tsx, packages/react-components/text/src/components/List/index.tsx, packages/react-components/text/src/components/Paragraph.tsx, packages/react-components/text/src/components/Small.tsx, packages/react-components/text/src/components/Strong.tsx, packages/react-components/text/src/components/Text.tsx, yarn.lock
Creates a new `childrenOfType` validator that extends the airbnb one we were previously using. This should now allow for emotion styled children to stop throwing warnings.
=> WF-469 Prop types errors

packages/react-components/modals/src/Panel/PanelStyles.ts, packages/react-components/modals/src/Panel/__snapshots__/index.spec.tsx.snap
When the width prop of a panel is set to a fixed width in pixels, the panel isn't restricted to 100% of the width on narrow screens as modals are. This small change makes panel behaviour similar to that of modals.
=> fix: make fixed size panel work on narrow screens

packages/react-components/text/src/components/Emphasis.tsx, packages/react-components/text/src/components/Heading.tsx, packages/react-components/text/src/components/Paragraph.tsx, packages/react-components/text/src/components/Small.tsx, packages/react-components/text/src/components/Strong.tsx, packages/react-components/text/src/components/Text.tsx
In order for the circular references to work in system JS bundles they need to be loaded this way
=> WF-475 move circular references to allow systemjs bundles

packages/react-components/form-elements/src/Input/index.spec.tsx, packages/react-components/form-elements/src/Input/index.tsx
This PR adds the `onFocus` prop to `Input`
=> feat: add onFocus prop to Input

packages/react-components/modals/src/AlertDialog/__snapshots__/index.spec.tsx.snap, packages/react-components/modals/src/BaseDialog/DialogStyles.ts, packages/react-components/modals/src/Dialog/__snapshots__/index.spec.tsx.snap
1. `transform: none` does no longer create a new coordinate system
2. `position: fixed` coordinates now correspond with `getBoundingClientRect()` values used by the positioner
3. `position: relative` contains the close button with `position: absolute` within the modal
Transform transition between scale(0.5) and none works.
A JS approach is hard because offsetParent of fixed elements inside a transformed element is null: [bugs.chromium.org/p/chromium/issues/detail?id=1086125
](bugs.chromium.org/p/chromium/issues/detail?id=1086125
)
Fix tested in Chrome, Firefox and Safari
=> fix: make positioner work in modals

packages/react-components/loaders/src/LogomarkSpinner.tsx, packages/react-components/loaders/src/__snapshots__/LogomarkSpinner.spec.tsx.snap
- position loader svg as block
- tweak numbers for this positioning
- simplify the loader container
- the inline positioning of the svg had a different relative effect at different sizes, changing some of the proportions the animations are based on at some sizes
=> fix: display loader svg as block

packages/docs/next-doc-site/components/code-preview.tsx, packages/docs/next-doc-site/components/colors-grid.tsx, packages/docs/next-doc-site/components/download-button.tsx, packages/docs/next-doc-site/components/editor.tsx, packages/docs/next-doc-site/components/example.tsx, packages/docs/next-doc-site/components/highlight.tsx, packages/docs/next-doc-site/components/icons-grid.tsx, packages/docs/next-doc-site/components/playground.tsx, packages/docs/next-doc-site/components/props-table.tsx, packages/docs/next-doc-site/components/table.tsx, packages/docs/next-doc-site/helpers/color-items-per-row.ts, packages/docs/next-doc-site/helpers/colors-from-tokens.ts, packages/docs/next-doc-site/helpers/component-metadata-by-name.ts, packages/docs/next-doc-site/helpers/type-name-from-metadata.ts, packages/docs/next-doc-site/package.json, packages/docs/next-doc-site/pages/_document.tsx, packages/docs/next-doc-site/pages/components/text.mdx, packages/docs/next-doc-site/pages/design/colors.mdx, packages/docs/next-doc-site/pages/design/icons.mdx, packages/docs/next-doc-site/pages/index.tsx, packages/docs/next-doc-site/types.ts, packages/react-components/text/src/components/Paragraph.tsx, yarn.lock
* Implemented **props table component**. It displays props parsed from provided component / module metadata (generated with _react-docgen_).
* Updated **editor** accessibility so it's no longer stuck when pressing Tab key.
* Simplified **Paragrpah** props checks, which was causing problems with MDX
* Added documentation for **Colors** and **Icons** pages
Props table:
Colors:
Icons:
=> [WF-489] Add Props table

packages/other/tokens/package.json, packages/other/utils/package.json, packages/other/utils/src/computeDataAttributes.ts, packages/other/utils/src/hexToRgbaColor.spec.ts, packages/other/utils/src/hexToRgbaColor.ts, packages/other/utils/src/index.spec.ts, packages/other/utils/src/index.ts, packages/react-components/button/package.json, packages/react-components/button/src/Button/buttonStyles.ts, packages/react-components/button/src/SocialMediaButtons/index.tsx, packages/react-components/card/package.json, packages/react-components/form-elements/package.json, packages/react-components/form-elements/src/CheckboxList/Checkbox.tsx, packages/react-components/form-elements/src/CheckboxList/index.tsx, packages/react-components/form-elements/src/Switch/Input.tsx, packages/react-components/form-elements/src/Switch/index.tsx, packages/react-components/form-elements/src/formStyles.ts, packages/react-components/modals/package.json, packages/react-components/modals/src/Dialog/StepsIndicator.tsx, packages/react-components/modals/src/sharedStyles.ts, packages/react-components/resizable-elements/package.json, packages/react-components/resizable-elements/src/ResizableElements.tsx, packages/react-components/text/package.json, packages/stylesheets/core/package.json, packages/stylesheets/core/test/core.spec.js, packages/tools/babel-preset/index.js, packages/tools/babel-preset/package.json, yarn.lock
Removed **lodash** wherever it made sense or where it was not used at all. Whole bundle size went down by **~600KB** uncompressed.
Replaced **tinycolor2** with custom function. **tinycolor2** is only left in **Text** package.
Passed **ref** to Switch component.
TODO:
Replace tinycolor2 in Text.
Before:
After:
=> Bundles size optimizations

packages/docs/storybook/stories/text.stories.js, packages/other/utils/src/hexColorLuminance.spec.ts, packages/other/utils/src/hexColorLuminance.ts, packages/other/utils/src/hexToRgbaColor.spec.ts, packages/other/utils/src/hexToRgbaColor.ts, packages/other/utils/src/index.spec.ts, packages/other/utils/src/index.ts, packages/react-components/text/package.json, packages/react-components/text/src/components/Badge.spec.tsx, packages/react-components/text/src/components/Badge.tsx, packages/react-components/text/src/components/__snapshots__/Badge.spec.tsx.snap, yarn.lock
Affected component: **Badge** from **Text**
Removed **tinyclor2** dependency, which saves around **35KB** uncompressed from **Text**.
Replaced tinycolor color calculations utils with custom ones.
The caveat is that now Badge could accept only HEX color values as background, but we should use tokens from our lib anyway.
Badge:
=> Remove tinyclor2

.circleci/config.yml
Docs are now deployed when hitting master.
=> fix: deploy only from master

packages/docs/next-doc-site/pages/components/form-elements.mdx, packages/react-components/form-elements/src/Switch/index.tsx
Fixed auto generated props table for **Switch** component by extracting it from forwardRef.
=> Fix Switch props docs

packages/docs/next-doc-site/examples/button/complete-user-account-menu.tsx, packages/docs/next-doc-site/pages/components/button.mdx, packages/react-components/button/src/Button/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/UserAccountMenu/AlertDot.tsx, packages/react-components/button/src/UserAccountMenu/Button.tsx, packages/react-components/button/src/UserAccountMenu/MenuItem.tsx, packages/react-components/button/src/UserAccountMenu/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/UserAccountMenu/index.spec.tsx
Added a possibility to show notification icon after passing **showAlertDot** prop to **MenuItem**:
=> Menu item notification

packages/other/utils/src/computeDataAttributes.spec.ts, packages/other/utils/src/computeDataAttributes.ts, packages/react-components/button/src/Button/buttonStyles.ts
Because of some errors reported by Sentry replaced **fromEntries** with regular reduce, for better old browser support.
Used `Object.keys` in the refactor, which is supported by IE11.
=> [FIX] Revert  usage of fromEntries

packages/docs/next-doc-site/examples/icons/customized.tsx, packages/docs/next-doc-site/pages/components/icons.mdx, packages/docs/storybook/stories/icons.stories.js, packages/react-components/button/src/Button/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/Button/index.tsx, packages/react-components/button/src/CloseButton/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/CloseButton/index.tsx, packages/react-components/button/src/SocialMediaButtons/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/UserAccountMenu/MenuItem.tsx, packages/react-components/button/src/UserAccountMenu/__snapshots__/index.spec.tsx.snap, packages/react-components/form-elements/src/CheckboxList/CheckboxIcon.tsx, packages/react-components/form-elements/src/CheckboxList/__snapshots__/index.spec.tsx.snap, packages/react-components/form-elements/src/Input/index.tsx, packages/react-components/form-elements/src/Select/__snapshots__/index.spec.tsx.snap, packages/react-components/form-elements/src/Switch/Toggle.tsx, packages/react-components/form-elements/src/Switch/__snapshots__/index.spec.tsx.snap, packages/react-components/form-elements/src/formStyles.ts, packages/react-components/icons/gulpfile.js, packages/react-components/markdown/src/components/__snapshots__/Markdown.spec.tsx.snap, packages/react-components/modals/src/AlertDialog/__snapshots__/index.spec.tsx.snap, packages/react-components/modals/src/Dialog/__snapshots__/index.spec.tsx.snap, packages/react-components/modals/src/Panel/__snapshots__/index.spec.tsx.snap, packages/react-components/text/src/components/Code.tsx, packages/react-components/text/src/components/CodeBlock.tsx, packages/react-components/text/src/components/__snapshots__/Code.spec.tsx.snap, packages/react-components/text/src/components/__snapshots__/CodeBlock.spec.tsx.snap, packages/react-components/toast/src/__snapshots__/index.spec.tsx.snap
Updated Waffles **Icons** sizes according to design guidelines:
- replace previous numeric values `12`, `18`, `24` with `xsmall`, `small`, and `medium` (which map to 12, 14, and 16px), to stay in line with new design tokens naming convention
- update all relevant components to use new icons
- update docs
Screenshot (icons medium size):
=> [WF-511] Update Icons sizes

packages/other/tokens/base-tokens.json, packages/other/tokens/test/__snapshots__/newTokens.spec.js.snap, packages/react-components/form-elements/src/Input/index.tsx, packages/react-components/text/src/components/__snapshots__/Link.spec.tsx.snap, packages/react-components/text/src/components/__snapshots__/Paragraph.spec.tsx.snap
Update **blueDarkText** token to meet a11y criteria for white and light beige backgrounds.
=> Update blueDarkText token

packages/react-components/markdown/package.json, packages/react-components/markdown/src/components/Markdown.spec.tsx, packages/react-components/markdown/src/components/Markdown.tsx, packages/react-components/markdown/src/components/__snapshots__/Markdown.spec.tsx.snap, yarn.lock
Bumped **react-markdown** version to **5.0.3** so it works with newer version of Webpack.
- ~[ ] Approved by Designer, Engineer, & PO~
=> Bump react-markdown dependency version

packages/react-components/markdown/package.json, packages/react-components/markdown/src/components/Markdown.spec.tsx, packages/react-components/markdown/src/components/Markdown.tsx, packages/react-components/markdown/src/components/__snapshots__/Markdown.spec.tsx.snap, yarn.lock
Bumped **react-markdown** version to **5.0.3** so it works with newer version of Webpack.
- ~[ ] Approved by Designer, Engineer, & PO~
=> Bump react-markdown for beta Markdown component

packages/other/tokens/buildNewTokens.js, packages/other/tokens/newTokensHelpers/tokensToEsModule.js, packages/other/tokens/newTokensHelpers/tokensToSassVariables.js, packages/other/tokens/newTokensHelpers/transformedBaseTokens.js, packages/other/tokens/test/__snapshots__/newTokens.spec.js.snap, packages/other/tokens/test/newTokens.spec.js, packages/react-components/button/src/UserAccountMenu/__snapshots__/index.spec.tsx.snap, packages/react-components/form-elements/src/Switch/__snapshots__/index.spec.tsx.snap
Parsed new design tokens to Sass variables, which will be exposed in `future-variables.scss` file in `@datacamp/waffles-tokens` package. Migration guide, although for JS file, is available [here](https://waffles.datacamp-staging.com/components/tokens/#migration-guide).
Content of the file (output of _buildNewTokens_ script):
```
$dc-sizing-small: 24px;
$dc-sizing-medium: 36px;
$dc-sizing-large: 48px;
$dc-spacing-xsmall: 4px;
$dc-spacing-small: 8px;
$dc-spacing-medium: 16px;
$dc-spacing-large: 24px;
$dc-spacing-xlarge: 32px;
$dc-navy-light: #213147;
$dc-navy: #05192D;
$dc-navy-dark: #000820;
$dc-navy-subtle-text-on-dark: #9BA3AB;
$dc-navy-subtle-text-on-light: #65707C;
$dc-green-light: #65FF8F;
$dc-green: #03EF62;
$dc-green-dark: #00C53B;
$dc-green-dark-text: #008700;
$dc-white: #FFFFFF; …
```
=> [WF-528] New design tokens as Sass variables

packages/docs/next-doc-site/examples/form-elements/auto-grow-textarea.tsx, packages/docs/next-doc-site/pages/components/form-elements.mdx, packages/docs/storybook/stories/form-elements.stories.js, packages/react-components/form-elements/src/TextArea/__snapshots__/index.spec.tsx.snap, packages/react-components/form-elements/src/TextArea/index.spec.tsx, packages/react-components/form-elements/src/TextArea/index.tsx, packages/react-components/form-elements/src/index.tsx
Added auto-grow functionality to **TextArea** component. It's enough to pass **autoGrow** prop:
Tested in various browsers and with screen readers. Custom styles overrides also work.
=> [WF-559] Auto-grow TextArea

.github/workflows/main.yml, packages/react-components/form-elements/src/Input/index.tsx
Fixed icon placement and right padding for **password** input type:
- ~[ ] Unit tests written & pass CI~
=> [WF-563] Fix password input

.github/workflows/main.yml, packages/react-components/form-elements/src/Input/index.tsx
Fixed right padding and icon placement for password **Input** component:
- ~[ ] Unit tests written & pass CI~
=> [WF-563] Fix password input padding (regular form elements)

packages/react-components/button/src/UserAccountMenu/Avatar.tsx, packages/react-components/button/src/UserAccountMenu/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/UserAccountMenu/index.tsx, packages/react-components/card/package.json, packages/react-components/card/src/index.spec.tsx, packages/react-components/card/src/index.tsx, packages/react-components/form-elements/src/CheckboxList/Checkbox.tsx, packages/react-components/form-elements/src/CheckboxList/index.spec.tsx, packages/react-components/form-elements/src/RadioList/Radio.tsx, packages/react-components/form-elements/src/RadioList/index.spec.tsx, packages/react-components/toast/package.json, packages/react-components/toast/src/Toast.tsx, packages/react-components/toast/src/__snapshots__/index.spec.tsx.snap, packages/react-components/toast/src/index.spec.tsx, packages/react-components/toast/src/index.tsx, packages/react-components/tooltip/src/index.spec.tsx, packages/react-components/tooltip/src/index.tsx
More components now accept **data** props:
* **Card**
* **Checkbox**
* **Radio**
* **Toast**
* **Tooltip**
Directly added Heap data attributes to _avatar image_ and _my profile link_ in **UserAccountMenu**.
**Switch** and **MenuItem** (UserAccountMenu subcomponent) accept `data-` attributes without custom API so no changes are required there.
Q: Do we need Tooltip inside button to be trackable? If yes, I will have to add something like `tooltipDataAttributes` there.
- ~[ ] Tested on [supported browsers](https://support.datacamp.com/hc/en-us/articles/360001541574-Minimum-System-Requirements)~
=> [WF-572] Heap support

packages/react-components/button/src/UserAccountMenu/Avatar.tsx, packages/react-components/button/src/UserAccountMenu/__snapshots__/index.spec.tsx.snap, packages/react-components/button/src/UserAccountMenu/index.tsx, packages/react-components/card/package.json, packages/react-components/card/src/index.spec.tsx, packages/react-components/card/src/index.tsx, packages/react-components/form-elements/src/CheckboxList/Checkbox.tsx, packages/react-components/form-elements/src/CheckboxList/index.spec.tsx, packages/react-components/form-elements/src/RadioList/Radio.tsx, packages/react-components/form-elements/src/RadioList/index.spec.tsx, packages/react-components/toast/package.json, packages/react-components/toast/src/Toast.tsx, packages/react-components/toast/src/__snapshots__/index.spec.tsx.snap, packages/react-components/toast/src/index.spec.tsx, packages/react-components/toast/src/index.tsx, packages/react-components/tooltip/src/index.spec.tsx, packages/react-components/tooltip/src/index.tsx
More components now accept **data** props:
* **Card**
* **Checkbox**
* **Radio**
* **Toast**
* **Tooltip**
Directly added Heap data attributes to _avatar image_ and _my profile link_ in **UserAccountMenu**.
**Switch** and **MenuItem** (UserAccountMenu subcomponent) accept `data-` attributes without custom API so no changes are required there.
- ~[ ] Tested on [supported browsers](https://support.datacamp.com/hc/en-us/articles/360001541574-Minimum-System-Requirements)~
=> [WF-572] Heap support for regular components

.circleci/config.yml, packages/react-components/button/src/UserAccountMenu/index.spec.tsx, packages/react-components/button/src/UserAccountMenu/index.tsx
To support new MFE Profiles allow custom **profileUrl** and **accountSettingUrl** to be provided.
=> UserAccountMenu custom profile URLs

packages/react-components/button/src/UserAccountMenu/index.spec.tsx, packages/react-components/button/src/UserAccountMenu/index.tsx
As a workaround to handle client side navigation, added custom onClick handler (**profileLinkOnClick**) for My Profile link. 
=> Profile link onClick handler

packages/react-components/modals/src/AlertDialog/__snapshots__/index.spec.tsx.snap, packages/react-components/modals/src/BaseDialog/index.tsx, packages/react-components/modals/src/Dialog/__snapshots__/index.spec.tsx.snap, packages/react-components/modals/src/Dialog/index.tsx
Add `backgroundColor` prop to `Dialog` component to unlock paywall feature in campus. I noticed **campus-app** is using  beta package, therefore making beta release too.
Mandatory ugly example with red background:
=> Adjustable Dialog background color
